### ISSUE TITLE
Duplicate info Duplicate info

### ISSUE THREAD

**Issue by MisinformedDNA** [aspnet/EntityFramework.ApiDocs#18]
A lot of the EF Core API Doc elements are being rendered twice. 

Here's some duplicates from https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.setcommandtimeout?view=efcore-2.0:
![image](https://user-images.githubusercontent.com/1784452/41379552-e105e364-6f27-11e8-9bf2-3fea8e3170d5.png)

On https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.databasefacade?view=efcore-2.0, I'm seeing triples:
![image](https://user-images.githubusercontent.com/1784452/41379671-326103ec-6f28-11e8-84f3-79db7c23fa72.png)

**Comment by mairaw** [comment]
Thanks @MisinformedDNA. I'm following up with the engineering team on this issue. /cc @dend 

 @divega can you confirm which languages would you like to see in the language dropdown?

**Comment by divega** [comment]
As discussed offline with @mairaw:

- We would like C#, VB and F# in the filter. We can consider adding C++ later if there is demand.
- We should not have the duplicate entries.
- The filter is broken:
   - C++ snippets are always shown
   - Selecting VB in the drop down shows C# snippets

**Comment by mairaw** [comment]
PR #21 fixed this issue.
