### ISSUE TITLE
Generate API docs for EF Core 2.2

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.ApiDocs#41]
We need the API for the 2.2.0 version of the packages 2.2.0 in the API browser.

**Comment by divega** [comment]
@dendeli-msft is this something that you can help with? I noticed that for .NET Core and ASP.NET Core, version 2.2 is already listed in the API browser.

**Comment by bricelam** [comment]
+1 I want this too. Any estimate on when this will be done? :trollface:

**Comment by smitpatel** [comment]
@mairaw - Can you guide us how to get this published or who would be right person to contact regarding this?

**Comment by smitpatel** [comment]
Fixed in #63
