### ISSUE TITLE
Clean up obsolete API reference?

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.ApiDocs#9]
We moved our API reference to the .NET site, but the old API reference is still in place at https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore. 

There is perhaps some value in keeping it in case there are external things pointing to it but on the other hand it does no good if it is stale. 

cc @dend.

**Comment by dend** [comment]
@divega we need to make sure that we set up redirects for it. I will help with that after the holidays.

**Comment by mairaw** [comment]
Has this ever been done @divega @dend?

**Comment by divega** [comment]
@mairaw no, as far as I know at least. Not sure how to delete it.

**Comment by mairaw** [comment]
We need to set up redirects in the backend. I've filed a request for this. Let's see if we can make it happen.

**Comment by divega** [comment]
@mairaw do you remember what the request number was or can check what happened?

**Comment by mairaw** [comment]
@divega let me see if I can find. I'm having some trouble finding some of my issues lately.

**Comment by mairaw** [comment]
Found it! Weird, they mark as completed. I'll reactivate.
https://dev.azure.com/mseng/CSI/_workitems/edit/1258920

**Comment by divega** [comment]
Now links to https://docs.microsoft.com/ef/core/api/microsoft.entityframeworkcore fail with 404, so this was cleaned up. But keeping this open until we figure out if it should redirect to the .NET API browser (see https://github.com/MicrosoftDocs/feedback/issues/824).

**Comment by mairaw** [comment]
Question @divega: was the previous content hosted in this same repo?

**Comment by divega** [comment]
@mairaw I didn't remember at all, but digging into [very old commits](https://github.com/aspnet/EntityFramework.ApiDocs/commit/286e23f9d382be6c7b70897bb4346943ff0baf32#diff-53ab02d9e015a595232c860138ca1d50) I think the answer is yes.

**Comment by divega** [comment]
@mairaw but also, we produce the conceptual documentation that also targets docs.microsoft.com/ef from https://github.com/aspnet/EntityFramework.Docs, so I think it would be fine to place the redirect there.

**Comment by smitpatel** [comment]
Redirects are in place and links no longer throw 404.
